linter:
  rules:
    - use_build_context_synchronously
    - prefer_interpolation_to_compose_strings
    - file_names
    - non_constant_identifier_names
    - avoid_unnecessary_containers
    - always_put_control_body_on_new_line
