name: shoppingapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  random_string: ^2.3.1
  shared_preferences: ^2.1.1
  image_picker: ^1.0.1
  firebase_storage: ^12.4.0
  flutter_stripe: ^11.3.0
  http: ^1.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
